<a href="https://colab.research.google.com/github/codybaraks/AUTOLIB-WEEK-4-MORINGA/blob/master/Independent_project_week_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# Importing numpy
import numpy as np

# Importing pandas
import pandas as pd

In [0]:
# Checking out the dataset
url = "http://bit.ly/Autolibdataset"

df = pd.read_csv(url)
df.to_csv('df.csv')

In [0]:
df = pd.read_csv('df.csv')

In [5]:
df.head(5)

   Unnamed: 0  Unnamed: 0.1                     Address  ...  day  hour  minute
0           0             0              24 Rue Vulpian  ...    1     0       0
1           1             1  8 Boulevard Richard Lenoir  ...    1     0       0
2           2             2        4 Rue Charles Bossut  ...    1     0       0
3           3             3   3 avenue Claude Vellefaux  ...    1     0       0
4           4             4      236 Boulevard Voltaire  ...    1     0       0

[5 rows x 27 columns]

In [6]:
# rename the column names

df.rename(columns={'Bluecar counter':'Bluecar_counter','Utilib counter':'Utilib_counter','Utilib 1.4 counter': 'Utilib_1.4_counter','Charge Slots':'Charge_Slots','Charging Status':'Charging_Status','Displayed comment':'Displayed_comment','Postal code':'Postal_code','Rental status':'Rental_status','Scheduled at':'Scheduled_at','Station type':'Station_type','Subscription status':'Subscription_status'})

          Unnamed: 0  Unnamed: 0.1  ... hour  minute
0                  0             0  ...    0       0
1                  1             1  ...    0       0
2                  2             2  ...    0       0
3                  3             3  ...    0       0
4                  4             4  ...    0       0
5                  5             5  ...    0       0
6                  6             6  ...    0       0
7                  7             7  ...    0       0
8                  8             8  ...    0       0
9                  9             9  ...    0       0
10                10            10  ...    0       0
11                11            11  ...    0       0
12                12            12  ...    0       0
13                13            13  ...    0       0
14                14            14  ...    0       0
15                15            15  ...    0       0
16                16            16  ...    0       0
17                17            17  ...    0       0
18                18            18  ...    0       0
19                19            19  ...    0       0
20                20            20  ...    0       0
21                21            21  ...    0       0
22                22            22  ...    0       0
23                23            23  ...    0       0
24                24            24  ...    0       0
25                25            25  ...    0       0
26                26            26  ...    0       0
27                27            27  ...    0       0
28                28            28  ...    0       0
29                29            29  ...    0       0
...              ...           ...  ...  ...     ...
14421799    14421799          1103  ...   23      59
14421800    14421800          1104  ...   23      59
14421801    14421801          1105  ...   23      59
14421802    14421802          1106  ...   23      59
14421803    14421803          1107  ...   23      59
14421804    14421804          1108  ...   23      59
14421805    14421805          1109  ...   23      59
14421806    14421806          1110  ...   23      59
14421807    14421807          1111  ...   23      59
14421808    14421808          1112  ...   23      59
14421809    14421809          1113  ...   23      59
14421810    14421810          1114  ...   23      59
14421811    14421811          1115  ...   23      59
14421812    14421812          1116  ...   23      59
14421813    14421813          1117  ...   23      59
14421814    14421814          1118  ...   23      59
14421815    14421815            97  ...   23      59
14421816    14421816           196  ...   23      59
14421817    14421817           234  ...   23      59
14421818    14421818           257  ...   23      59
14421819    14421819           372  ...   23      59
14421820    14421820           545  ...   23      59
14421821    14421821           605  ...   23      59
14421822    14421822           634  ...   23      59
14421823    14421823           759  ...   23      59
14421824    14421824           880  ...   23      59
14421825    14421825           950  ...   23      59
14421826    14421826           996  ...   23      59
14421827    14421827          1010  ...   23      59
14421828    14421828          1072  ...   23      59

[14421829 rows x 27 columns]

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14421829 entries, 0 to 14421828
Data columns (total 26 columns):
Unnamed: 0             int64
Address                object
Cars                   int64
Bluecar counter        int64
Utilib counter         int64
Utilib 1.4 counter     int64
Charge Slots           int64
Charging Status        object
City                   object
Displayed comment      object
ID                     object
Kind                   object
Geo point              object
Postal code            int64
Public name            object
Rental status          object
Scheduled at           object
Slots                  int64
Station type           object
Status                 object
Subscription status    object
year                   int64
month                  int64
day                    int64
hour                   int64
minute                 int64
dtypes: int64(13), object(13)
memory usage: 2.8+ GB

In [12]:
# DATA CLEANING
# Lowering the columns
# df1.columns = map(str.lower, df1.columns)
# df1.head()
# df.drop(df.columns=['Displayed comment', 'Scheduled at'])
# df.drop(['Displayed comment', 'Scheduled at'], axis =1,inplace  =True
# df.drop(['Slots','minute'], axis =1,inplace = True)


df.head(3)

   Unnamed: 0                     Address  Cars  ...  day  hour  minute
0           0              24 Rue Vulpian     3  ...    1     0       0
1           1  8 Boulevard Richard Lenoir     0  ...    1     0       0
2           2        4 Rue Charles Bossut     3  ...    1     0       0

[3 rows x 26 columns]

In [14]:
# df = pd.read_csv('df.csv')
df.head()

   Unnamed: 0                     Address  Cars  ...  day  hour  minute
0           0              24 Rue Vulpian     3  ...    1     0       0
1           1  8 Boulevard Richard Lenoir     0  ...    1     0       0
2           2        4 Rue Charles Bossut     3  ...    1     0       0
3           3   3 avenue Claude Vellefaux     4  ...    1     0       0
4           4      236 Boulevard Voltaire     1  ...    1     0       0

[5 rows x 26 columns]

In [0]:
# DATA CLEANING
# Renaning the columns
# df1.rename(columns={'Bluecar counter':'Bluecar_counter','Utilib counter': 'Utilib_counter', 'Utilib 1.4 counter': 'Utilib_1.4_counter','Charge Slots':'Charge_Slots','Charging_Status':'Households_Grass','%_of_Households_Makuti':'Households_Makuti','%_of_Households_Tin':'Households_Tin','%_of_Households_Mud/Dung':'Households_Mud_Dung','%_of_Households_Other':'Households_Other','No_Mud/Dung':'No_Mud_Dung'})

df = df.rename(columns={'Bluecar counter':'Bluecar_counter','Utilib counter':'Utilib_counter','Utilib 1.4 counter': 'Utilib_1.4_counter','Charge Slots':'Charge_Slots','Charging Status':'Charging_Status','Displayed comment':'Displayed_comment','Postal code':'Postal_code','Rental status':'Rental_status','Scheduled at':'Scheduled_at','Station type':'Station_type','Subscription status':'Subscription_status'})

In [10]:
df.head()

                      Address  Bluecar_counter  ...  hour  minute
0              24 Rue Vulpian                3  ...     0       0
1  8 Boulevard Richard Lenoir                0  ...     0       0
2        4 Rue Charles Bossut                3  ...     0       0
3   3 avenue Claude Vellefaux                4  ...     0       0
4      236 Boulevard Voltaire                1  ...     0       0

[5 rows x 15 columns]

In [2]:
dff = pd.read_csv('dff.csv')
dff.head()

   Unnamed: 0  Unnamed: 0.1  Unnamed: 0.1.1  ... day  hour  minute
0           0             0               0  ...   1     0       0
1           1             1               1  ...   1     0       0
2           2             2               2  ...   1     0       0
3           3             3               3  ...   1     0       0
4           4             4               4  ...   1     0       0

[5 rows x 28 columns]

#Completeness

In [11]:
# Check the number of missing values
df.isnull().any()

Address               False
Bluecar_counter       False
Utilib_counter        False
Utilib_1.4_counter    False
Charge_Slots          False
Charging_Status       False
City                  False
Kind                  False
Postal_code           False
Public name           False
Slots                 False
Status                False
day                   False
hour                  False
minute                False
dtype: bool

In [12]:
# Check the sum of the total number of missing values
df.isnull().sum().sum()

0

# Consistency

In [6]:
# Check the duplicates 
check_duplicates = df.duplicated()
check_duplicates
# Delete duplicates
df.drop_duplicates()

                                            Address  ...  minute
0                                    24 Rue Vulpian  ...       0
1                        8 Boulevard Richard Lenoir  ...       0
2                              4 Rue Charles Bossut  ...       0
3                         3 avenue Claude Vellefaux  ...       0
4                            236 Boulevard Voltaire  ...       0
5                      44 Rue des Pirogues de Bercy  ...       0
6                       63 Boulevard Richard Lenoir  ...       0
7                                 43 Rue de Monceau  ...       0
8                10 Avenue du Docteur Arnold Netter  ...       0
9                    33 Avenue Pierre 1er de Serbie  ...       0
10                         2 Rue Houdart de Lamotte  ...       0
11                238 Rue du Faubourg Saint-Antoine  ...       0
12                               23 Quai aux Fleurs  ...       0
13                            54 Rue David d'Angers  ...       0
14                                46 rue de Turenne  ...       0
15                              142 Rue de Bagnolet  ...       0
16                   91 rue du Faubourg Saint-Denis  ...       0
17                                 336 Rue Lecourbe  ...       0
18                         16 place des Ãtats-Unis  ...       0
19                                     99 Rue Monge  ...       0
20                      45 Avenue de la Bourdonnais  ...       0
21                                    42 Rue du Bac  ...       0
22                           42 avenue de Friedland  ...       0
23                               143 Rue La Fayette  ...       0
24                           182 Boulevard Voltaire  ...       0
25                         2 Rue Fabre d'Ãglantine  ...       0
26                            4 Avenue Jean JaurÃ¨s  ...       0
27                           30 Quai de Dion Bouton  ...       0
28                          183 Rue des Renouillers  ...       0
29                              5 Place du Commerce  ...       0
...                                             ...  ...     ...
14421785                              42 rue Brunel  ...      59
14421786                  61 rue Pierre Brossolette  ...      59
14421787                     30 rue Marcel Bontemps  ...      59
14421788                    77 rue Edouard Vaillant  ...      59
14421789                            1 rue de Sevran  ...      59
14421790                             14 rue Censier  ...      59
14421791                             9 rue Lobineau  ...      59
14421792                            29 rue GalilÃ©e  ...      59
14421793                        1 rue de YÃ©limanÃ©  ...      59
14421794            15 place du GÃ©nÃ©ral de Gaulle  ...      59
14421795                     53 rue du Bois l'AbbÃ©  ...      59
14421796                            18 rue Franklin  ...      59
14421797                 4 Chemin des petits marais  ...      59
14421798                      93 avenue Victor Hugo  ...      59
14421799  106 avenue du Vieux Chemin de Saint-Denis  ...      59
14421800                              4 rue Valiton  ...      59
14421801                          53 Boulevard Foch  ...      59
14421802                               5 rue Vauban  ...      59
14421803                68 rue de la Bonne Aventure  ...      59
14421804            1 avenue du GÃ©nÃ©ral de Gaulle  ...      59
14421805                 4 boulevard Anatole France  ...      59
14421806                  2 avenue Georges Pompidou  ...      59
14421807                         12 avenue Rabelais  ...      59
14421808                    1 rue de la LibÃ©ration  ...      59
14421809                    282 avenue d'Argenteuil  ...      59
14421810              21 rue de l'Ecole de Medecine  ...      59
14421811         6 avenue de la Porte de Champerret  ...      59
14421812                        194 rue de fontenay  ...      59
14421813            102 Boulevard Raymond PoincarÃ©  ...      59
14421814                       8 avenue George Sand  ...      59

[14278939 rows x 15 columns]

In [5]:
# Dealing with missing data
dff_no_missing = dff.dropna()
dff_no_missing.head(3)

   Unnamed: 0.1.1                     Address  ...  hour  minute
0               0              24 Rue Vulpian  ...     0       0
1               1  8 Boulevard Richard Lenoir  ...     0       0
2               2        4 Rue Charles Bossut  ...     0       0

[3 rows x 16 columns]

In [4]:
# Check the number of cities in paris
cities = df[df['City'] == 'Paris']
cities.count()

Unnamed: 0             7874596
Unnamed: 0.1           7874596
Address                7874596
Cars                   7874596
Bluecar counter        7874596
Utilib counter         7874596
Utilib 1.4 counter     7874596
Charge Slots           7874596
Charging Status        7874596
City                   7874596
Displayed comment       180429
ID                     7874596
Kind                   7874596
Geo point              7874596
Postal code            7874596
Public name            7874596
Rental status          7874596
Scheduled at             25772
Slots                  7874596
Station type           7874596
Status                 7874596
Subscription status    7874596
year                   7874596
month                  7874596
day                    7874596
hour                   7874596
minute                 7874596
dtype: int64

##Research Question SECTION

In [16]:
# Identify the most popular hour of the day for picking up a shared electric car (Bluecar) in the city of Paris over the month of April 2018
# Overall?
# x = dff["Slots"].min()
# x
df[(df.City == 'Paris') & (df.Bluecar_counter	< 4)].groupby('hour')['hour'].count().sort_values(ascending = False).head(1)

hour
19    280496
Name: hour, dtype: int64

In [27]:
df["Bluecar counter"].min()
df["Bluecar counter"].max()

7

In [25]:
# What is the most popular hour for returning cars?
# I found the min = "0" and max = "7", then got the average, so i compared the average value 
# to the value of blue counter
df[df['Bluecar counter'] < 4].groupby('hour')['hour'].count().sort_values(ascending= False)

hour
19    461400
18    456899
17    448477
20    446951
16    437582
15    430617
14    424614
13    423932
12    423899
21    422800
11    413741
10    407204
9     406955
22    403261
8     400291
7     377266
2     370632
3     363832
6     362697
4     361956
5     361532
23    359353
0     348141
1     337079
Name: hour, dtype: int64

In [8]:
# What postal code is the most popular for picking up Bluecars? Does the most popular station belong to that postal code?
# Overall?
# popular = dff.groupby("Postal code")["Bluecar counter"].min()
# dff[["Postal code","Bluecar counter","ID"]].sort_values["Postal code"]
# What station is the most popular?
# Overall?

df[(df['Kind'] == 'STATION') & (df['Status'] == 'ok')].groupby('Public name')['Public name'].count().sort_values(ascending= False)

Public name
Paris/UzÃ¨s/1                                12927
Paris/Sibelle/29                             12922
Paris/Ramey/62                               12920
Bagnolet/Pasteur/124                         12918
Paris/Maine/185                              12917
Paris/Dante/1                                12915
Aulnay-sous-bois/Maryse BastiÃ©/1            12915
Montreuil/GalilÃ©e/29                        12914
Paris/Louis Blanc/6                          12914
Colombes/Seine/52                            12914
Paris/Bosquet/41                             12913
Paris/Simon Bolivar/96                       12913
Paris/Jean-Jacques Rousseau/62               12912
Paris/Caulaincourt/71                        12912
Paris/Martignac/2                            12912
Paris/Chevaleret/79                          12911
Nanterre/Hoche/1                             12911
Nanterre/Lens/13                             12911
Bezons/Emile Zola/50                         12911
Courbevoie/Paix/2                            12911
Paris/Grenelle/37                            12911
Paris/Pierre Brossolette/1                   12910
Cachan/Pont Royal/24                         12910
Paris/Victor Hugo/180                        12910
Paris/Fabre d'Ãglantine/2                   12910
Nanterre/Ecoles/5                            12910
Paris/Didot/41                               12910
Gennevilliers/CamÃ©linat/66                  12909
Paris/Jean de la Fontaine/42                 12909
Paris/Pernety/46                             12909
                                             ...
Vanves/Larmeroux/12                          12330
Paris/Tolbiac/41                             12314
Paris/Eaux/2                                 12296
Paris/Finlay/43                              12164
Villejuif/Marcel Paul/6                      12040
AsniÃ¨res-sur-Seine/Argenteuil/152           11976
Paris/Monge/99                               11864
Paris/ChÃ¢teau Landon/52                     11798
ChÃ¢tenay-Malabry/Cyrano de Bergerac/6       11631
Argenteuil/Aristide Briand/1                 11499
Paris/Rocroy/15                              11498
Paris/La Fayette/143                         11490
Paris/Faubourg-Saint-Martin/168              11464
Paris/Caulaincourt/17                        11442
Paris/Londres/6                              11409
Colombes/Pierre Brossolette/42               11355
Paris/Sibour/2                               11276
La Garenne-Colombes/National/31              11155
Paris/Capitaine Ferber/5                     10837
Chaville/Anatole France/28                   10320
Paris/Courcelles/210                          9083
Paris/Gambetta/65                             8586
Paris/Saint-HonorÃ©/91                        7836
Pantin/CimetiÃ¨re Parisien/34                 7785
Saint-Denis/Gabriel PÃ©ri/3                   7340
Nanterre/RÃ©publique/326                      5946
Issy-les-Moulineaux/Camille Desmoulins/31     5717
Sceaux/Houdan/118                             4556
Saint-Denis/Cheminots/24                      4379
Paris/Roquette/162                            4162
Name: Public name, Length: 931, dtype: int64

In [10]:
# At the most popular picking hour
# pick = dff.groupby("hour", sort=False)["Bluecar counter"].nunique()
# pick.min()
# At the most popular picking hour?
df[(df['Kind'] == 'STATION') & (df['Status'] == 'ok') & (df['hour'] == 4)].groupby('Public name')['Public name'].count().sort_values(ascending= False)

Public name
Paris/Bosquet/41                             554
Paris/Manin/159                              553
Paris/Grange aux Belles/11                   553
Paris/Mademoiselle/22                        553
Le Plessis-Robinson/Aristide Briand/51       553
Drancy/Roger Salengro/97                     553
Paris/Raymond PoincarÃ©/51                   553
SÃ¨vres/Riocreux/1                           552
Paris/Artois/11                              552
Boulogne-Billancourt/Alphonse Le Gallo/35    552
Paris/Molitor/16                             552
Paris/Mayet/2                                552
Paris/Dantzig/37                             551
Vanves/Larmeroux/12                          551
Paris/Batignolles/9                          551
AsniÃ¨res-sur-Seine/Marne/44                 551
Sceaux/Paul Langevin/3                       551
Paris/Martignac/2                            551
Paris/Ãcoles/19                             551
Paris/Lyon/8                                 551
Paris/Maine/185                              551
Nanterre/Lens/13                             551
Rungis/Lard/22                               551
Paris/Jean Moulin/34                         551
Vincennes/Fontenay/44                        551
Paris/Lorraine/22                            550
Paris/Jean-Jacques Rousseau/62               550
Paris/BrÃ©montier/19                         550
AsniÃ¨res-sur-Seine/Ãmile Zola/17           550
Paris/Saint-MandÃ©/94                        550
                                            ...
Rueil-Malmaison/Albert 1er/2                 540
Paris/Sept Arpents/9                         540
Montreuil/RÃ©publique/2                      540
Paris/Fernand Braudel/21                     540
Montreuil/Roches/22                          540
Malakoff/Stalingrad/27                       540
Paris/Londres/6                              496
Paris/Caulaincourt/17                        486
Paris/Sibour/2                               486
Argenteuil/Aristide Briand/1                 485
Chaville/Anatole France/28                   485
AsniÃ¨res-sur-Seine/Argenteuil/152           485
Paris/Faubourg-Saint-Martin/168              485
Paris/ChÃ¢teau Landon/52                     484
Paris/La Fayette/143                         484
La Garenne-Colombes/National/31              484
Paris/Capitaine Ferber/5                     483
Paris/Rocroy/15                              482
Colombes/Pierre Brossolette/42               481
ChÃ¢tenay-Malabry/Cyrano de Bergerac/6       426
Paris/Gambetta/65                            425
Paris/Courcelles/210                         363
Paris/Saint-HonorÃ©/91                       305
Pantin/CimetiÃ¨re Parisien/34                304
Saint-Denis/Gabriel PÃ©ri/3                  301
Issy-les-Moulineaux/Camille Desmoulins/31    244
Nanterre/RÃ©publique/326                     242
Sceaux/Houdan/118                            182
Paris/Roquette/162                           182
Saint-Denis/Cheminots/24                     182
Name: Public name, Length: 931, dtype: int64

In [11]:
# What postal code is the most popular for picking up Bluecars? Does the most popular station belong to that postal code?
# Overall?

df[(['Kind'] == 'STATION') & (df['Status'] == 'ok')].groupby('Postal code')['Postal code'].count().sort_values(ascending= False)

Series([], Name: Postal code, dtype: int64)

In [12]:
# At the most popular picking hour? for blue cars
df[(df['Kind'] == 'STATION') & (df['Status'] == 'ok') & (df['hour'] == 4)].groupby('Postal code')['Postal code'].count().sort_values(ascending= False)

Postal code
75015    27274
75016    23459
75017    19983
75013    19616
75020    18906
75012    16929
75019    16913
92000    16618
75008    16145
75014    15832
75011    14909
75018    14682
75007    12553
75010    12243
75009    11415
92500    10912
92130    10603
75005     9817
94000     9272
75006     8718
93100     7630
75004     7622
92700     7580
92100     7097
92150     7083
92600     7029
93700     6544
75003     6537
92140     6007
75002     5992
         ...
92370     1579
93230     1096
92420     1096
94220     1096
94150     1095
93130     1094
91370     1093
92110     1093
93350     1092
92360     1091
94340     1091
93260     1091
95870     1090
94450     1090
95880     1088
92390     1087
93200     1025
92290      974
92410      547
93310      546
75112      546
93150      545
75116      545
91400      545
94100      544
92340      543
94700      543
93300      542
94410      542
92200      541
Name: Postal code, Length: 100, dtype: int64

#Utilib and Utilib 1.4 section

In [15]:
# Do the results change if you consider Utilib and Utilib 1.4 instead of Bluecars? 
# (that could be asked earlier to push students to write modular code that can be
# used to query different things)
df.head()

# Electric2.head()
# Electric_paris[Electric_paris['Utilib_two_Diff'] < 0].groupby('hour')['hour'].count().sort_values(ascending= False)

   Unnamed: 0  Unnamed: 0.1                     Address  ...  day  hour  minute
0           0             0              24 Rue Vulpian  ...    1     0       0
1           1             1  8 Boulevard Richard Lenoir  ...    1     0       0
2           2             2        4 Rue Charles Bossut  ...    1     0       0
3           3             3   3 avenue Claude Vellefaux  ...    1     0       0
4           4             4      236 Boulevard Voltaire  ...    1     0       0

[5 rows x 27 columns]

In [0]:
df['Utilib_Diff'] = df['Utilib counter'].diff()
# this is inorder to find the difference in the number of utilib

In [18]:
# Identify the most popular hour of the day for picking up a shared electric car Utilib in the city of Paris over the month of April 2018
df[df['Utilib_Diff'] < 0].groupby('hour')['hour'].count().sort_values(ascending= False)

hour
5     38624
6     38508
4     38266
7     38222
3     37991
2     37703
8     36912
9     35219
10    35125
21    34139
11    33876
22    33682
14    33574
13    33520
1     33097
12    32805
15    32799
16    32797
0     32204
20    32187
23    31718
17    31133
19    30902
18    30101
Name: hour, dtype: int64

In [19]:
#  the most popular hour for returning cars? Utilib
df[df['Utilib_Diff'] > 0].groupby('hour')['hour'].count().sort_values(ascending= False)

hour
5     38484
6     38450
7     38141
4     38101
3     37932
2     37686
8     36719
9     35289
10    35123
21    34080
11    33763
22    33642
14    33600
13    33474
1     33107
15    32799
16    32792
12    32712
20    32169
0     32155
23    31766
17    31096
19    30871
18    30077
Name: hour, dtype: int64

In [20]:
# Most popular picking hour in relation to Utilib
df[df['Utilib_Diff'] > 0].groupby('hour')['hour'].count().sort_values(ascending= False)

hour
5     38484
6     38450
7     38141
4     38101
3     37932
2     37686
8     36719
9     35289
10    35123
21    34080
11    33763
22    33642
14    33600
13    33474
1     33107
15    32799
16    32792
12    32712
20    32169
0     32155
23    31766
17    31096
19    30871
18    30077
Name: hour, dtype: int64

In [21]:
#  What postal code is the most popular for picking up Utilib Counter? Does the most popular station belong to that postal code?
df[(df['Kind'] == 'STATION') & (df['Status'] == 'ok') & (df['hour'] == 5)].groupby('Postal code')['Postal code'].count().sort_values(ascending= False)

Postal code
75015    27272
75016    23472
75017    20019
75013    19623
75020    18881
75019    16904
75012    16898
92000    16613
75008    16100
75014    15830
75011    14916
75018    14681
75007    12545
75010    12227
75009    11383
92500    10917
92130    10619
75005     9820
94000     9273
75006     8731
75004     7650
93100     7639
92700     7576
92100     7094
92150     7087
92600     7033
93700     6556
75003     6552
92140     5998
75002     5986
         ...
92370     1549
93230     1097
93350     1094
92360     1093
94150     1093
92390     1092
94340     1092
91370     1091
93130     1091
92110     1090
94450     1090
95870     1088
93260     1088
94220     1086
95880     1084
92420     1083
93200     1027
92290     1027
92200      547
94700      547
93310      546
92410      546
75112      546
93150      545
75116      545
93300      544
92340      544
94410      544
91400      542
94100      540
Name: Postal code, Length: 100, dtype: int64

In [22]:
df[(df['Kind'] == 'STATION') & (df['Status'] == 'ok') & (df['hour'] == 4)].groupby('Public name')['Public name'].count().sort_values(ascending= False)

Public name
Paris/Bosquet/41                             554
Paris/Manin/159                              553
Paris/Grange aux Belles/11                   553
Paris/Mademoiselle/22                        553
Le Plessis-Robinson/Aristide Briand/51       553
Drancy/Roger Salengro/97                     553
Paris/Raymond PoincarÃ©/51                   553
SÃ¨vres/Riocreux/1                           552
Paris/Artois/11                              552
Boulogne-Billancourt/Alphonse Le Gallo/35    552
Paris/Molitor/16                             552
Paris/Mayet/2                                552
Paris/Dantzig/37                             551
Vanves/Larmeroux/12                          551
Paris/Batignolles/9                          551
AsniÃ¨res-sur-Seine/Marne/44                 551
Sceaux/Paul Langevin/3                       551
Paris/Martignac/2                            551
Paris/Ãcoles/19                             551
Paris/Lyon/8                                 551
Paris/Maine/185                              551
Nanterre/Lens/13                             551
Rungis/Lard/22                               551
Paris/Jean Moulin/34                         551
Vincennes/Fontenay/44                        551
Paris/Lorraine/22                            550
Paris/Jean-Jacques Rousseau/62               550
Paris/BrÃ©montier/19                         550
AsniÃ¨res-sur-Seine/Ãmile Zola/17           550
Paris/Saint-MandÃ©/94                        550
                                            ...
Rueil-Malmaison/Albert 1er/2                 540
Paris/Sept Arpents/9                         540
Montreuil/RÃ©publique/2                      540
Paris/Fernand Braudel/21                     540
Montreuil/Roches/22                          540
Malakoff/Stalingrad/27                       540
Paris/Londres/6                              496
Paris/Caulaincourt/17                        486
Paris/Sibour/2                               486
Argenteuil/Aristide Briand/1                 485
Chaville/Anatole France/28                   485
AsniÃ¨res-sur-Seine/Argenteuil/152           485
Paris/Faubourg-Saint-Martin/168              485
Paris/ChÃ¢teau Landon/52                     484
Paris/La Fayette/143                         484
La Garenne-Colombes/National/31              484
Paris/Capitaine Ferber/5                     483
Paris/Rocroy/15                              482
Colombes/Pierre Brossolette/42               481
ChÃ¢tenay-Malabry/Cyrano de Bergerac/6       426
Paris/Gambetta/65                            425
Paris/Courcelles/210                         363
Paris/Saint-HonorÃ©/91                       305
Pantin/CimetiÃ¨re Parisien/34                304
Saint-Denis/Gabriel PÃ©ri/3                  301
Issy-les-Moulineaux/Camille Desmoulins/31    244
Nanterre/RÃ©publique/326                     242
Sceaux/Houdan/118                            182
Paris/Roquette/162                           182
Saint-Denis/Cheminots/24                     182
Name: Public name, Length: 931, dtype: int64

In [23]:
# Most popular postal code for picking up utilib
df[(df['Kind'] == 'STATION') & (df['Status'] == 'ok') & (df['hour'] == 4)].groupby('Postal code')['Postal code'].count().sort_values(ascending= False)

Postal code
75015    27274
75016    23459
75017    19983
75013    19616
75020    18906
75012    16929
75019    16913
92000    16618
75008    16145
75014    15832
75011    14909
75018    14682
75007    12553
75010    12243
75009    11415
92500    10912
92130    10603
75005     9817
94000     9272
75006     8718
93100     7630
75004     7622
92700     7580
92100     7097
92150     7083
92600     7029
93700     6544
75003     6537
92140     6007
75002     5992
         ...
92370     1579
93230     1096
92420     1096
94220     1096
94150     1095
93130     1094
91370     1093
92110     1093
93350     1092
92360     1091
94340     1091
93260     1091
95870     1090
94450     1090
95880     1088
92390     1087
93200     1025
92290      974
92410      547
93310      546
75112      546
93150      545
75116      545
91400      545
94100      544
92340      543
94700      543
93300      542
94410      542
92200      541
Name: Postal code, Length: 100, dtype: int64